#!/usr/bin/env python
"""
Debug what models are being generated by the search
"""

import pyoccam2

def debug_search():
    """Debug model generation in search"""
    
    print("=" * 70)
    print("SEARCH MODEL GENERATION DEBUG")
    print("=" * 70)
    
    # Initialize manager
    manager = pyoccam2.VBMManager()
    success = manager.init_from_command_line(["occam", "dementia05.txt"])
    
    if not success:
        print("ERROR: Failed to load data")
        return
    
    # Enable debug mode to see what's generated
    manager.set_debug_mode(True)
    
    print("\nRunning search with debug output...")
    print("-" * 50)
    
    # Run search for just 1 level with width=18 to see all generated models
    search_report = manager.generate_search_report("loopless-up", levels=1, width=18)
    
    # Get the kept models
    kept = manager.get_kept_models()
    
    print("\n" + "=" * 70)
    print("FINAL KEPT MODELS:")
    print("-" * 50)
    
    level1 = [m for m in kept if m.level == 1]
    for i, model in enumerate(level1, 1):
        print(f"{i:2d}. {model.name:<10} BIC={model.bic:8.2f} Info={model.information:.4f}")
    
    print("\n" + "=" * 70)
    print("EXPECTED TOP MODELS (from server):")
    print("-" * 50)
    print("1. IV:ApZ (APOE) - should have best BIC")
    print("2. IV:EdZ (Education)")
    print("3. IV:AgZ (AgeLastExam)")
    
    # Check if APOE model exists
    apz_found = any(m.name == "IV:ApZ" for m in level1)
    if not apz_found:
        print("\n⚠️ WARNING: IV:ApZ (APOE) was not found in search results!")
        print("This means it was never generated by search->search()")

if __name__ == "__main__":
    debug_search()