#! /bin/sh

# Set PYTHONHOME based on pkg installation. The python package must be made
# visible to your shell first

PYTHONHOME=/usr/bin/python
export PYTHONHOME

# This can be changed to use a different script.
if test -z "$1"
then
    echo "Usage: occam3 datafile"
    echo "  or, occam3 scriptfile datafile"
    exit 0
fi

if test -z "$2"
then
    SCRIPT=basic.py
    DATA=$1
else
    SCRIPT=$1
    DATA=$2
fi

echo "Using script $SCRIPT"

# Usage: occam3 <datafile>
python $SCRIPT $DATA
